### PR TITLE
problem:: we are still using lux.min.css

### PR DESCRIPTION
**Pull request by AshHimself**
solution: implement the bootwatch npm module and remove all other lux css files #1535

### CODE REVIEW

**Comment by anbud** [comment]
@AshHimself, Meteor refuses to build on Windows after this PR. The error is:
```
=> Errors prevented startup:

   While processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: File to import:
   {}/node_modules/bootswatch/dist/lux/_variables.scss not found in file:
   C:/blockrazor/{}/client/main.scss
```

I've tried changing imports to absolute paths, but that doesn't work. I've tried using [global imports](https://github.com/fourseven/meteor-scss#global-include-path) without luck. I've also tried updating `fourseven:scss` to 4.9.0, but that produces the following error:
```
While loading plugin `compileScssBatch` from package `fourseven:scss`:
   packages/meteor.js:1434:9: Package._define is not a function
```

I'm guessing everything works fine on Linux machines as tests are properly passing.
Do you have any ideas? :)

**Comment by samuelralak** [comment]
@anbud I got the same error locally. I ran `meteor npm install` then `meteor run` - this resolved the issue for me. Though there appears to be some broken css styles through out the application

**Comment by anbud** [comment]
@samuelralak, thank you!

I've run `meteor npm install` before, but I was starting Meteor with only `meteor` and it didn't work. I've switched to `meteor run` and it works now. That's quite weird, I thought `meteor` and `meteor run` are the same thing.

**Comment by samuelralak** [comment]
found that weird too. both commands should naturally work the same way. its expected that `run` should be the deafult command for `meteor`

**Comment by AshHimself** [comment]
So you guys all good? I have no idea why this is the case and honestly i never test my builds on windows :D

**Comment by anbud** [comment]
Yap, everything works now. Don't worry about it, I don't test my builds on Linux either. :D

**Pull request merged**
