### PR TITLE
#1322 fixed image path in moderator approval page

### PR DESCRIPTION
**Pull request by jigartankhupp**
Solution : Replaced `currencyReview.currencyName.currencyLogoFilename` with `currencyReview.currencyLogoFilename`

### CODE REVIEW

**Comment by gazhayes** [comment]
Hi Jigar,

Why are you putting dump.tar.gz into the repository?

Also, this doesn't follow the C4 contribution protocol. Please check the Readme and try again.

**Comment by jigartankhupp** [comment]
Updating PR immediately.

**Comment by samuelralak** [comment]
Hi @jigartankhupp this PR still doesn't comply with the [C4 Contribution Policy](https://github.com/Blockrazor/blockrazor/blob/master/CONTRIBUTING.MD). I would also advise reading through the [step by step guide](https://github.com/Blockrazor/blockrazor#contributing-to-blockrazor) again on how to send proper PR in [README.MD](https://github.com/Blockrazor/blockrazor/blob/master/README.md). You are free to submit another [C4 compliant](https://github.com/Blockrazor/blockrazor/blob/master/CONTRIBUTING.MD) PR.

**Comment by jigartankhupp** [comment]
The path given was wrong in admin panel for currency image. It wasn't t the same to which the image was being uploaded. So it needed just a minor tweak.

**Comment by jigartankhupp** [comment]
@blockrazorbot remove "done"

**Comment by jigartankhupp** [comment]
@gazhayes Can you take a look now ?

**Comment by gazhayes** [comment]
Every commit should be solving a discrete problem. The way you specify what problem you are solving is to say "problem:......" In the commit message. This is all documented in the Readme and the C4.

**Comment by gazhayes** [comment]
And for this small issue you only need 1 commit.

**Comment by jigartankhupp** [comment]
Will come up C4 compliant PR as per your last comments.

**Pull request closed without merging**
