### PR TITLE
Fixed errors in imports/ui/components/typehead.css

### PR DESCRIPTION
**Pull request by Ayanrocks**
Problem: "Errors in typehead.css file and display set to inline-block while using float"
solution:  I have fixed the error in typhead.css file and have remove conflict in display property with float

### CODE REVIEW

**Comment by samuelralak** [comment]
Hello there @Ayanrocks, this PR doesn't seem to conform to the Project's C4 contribution policy outlined in the contribution protocol [here](https://github.com/Blockrazor/blockrazor/blob/master/CONTRIBUTING.MD). It would be worth going through the [README](https://github.com/Blockrazor/blockrazor#contributing-to-blockrazor) and find out how you can submit a better PR.

**Comment by Ayanrocks** [comment]
Well i have read the readme.md and done everything except creating another branch.

**Comment by samuelralak** [comment]
@Ayanrocks not entirely everything sir. For instance, your patch needs to address one of the problems logged on the Project's issue tracker - alternatively, if an issue does not exist you can always create a new one by describing the problem you are facing or observed and a simple solution but accurate solution to it if any.

Your commit message also needs to contain the problem thats being solved by the patch and a solution statement describing how exactly you solved that particular problem.

@Ayanrocks it would be worth going through the [README](https://github.com/Blockrazor/blockrazor#blockrazor) and [C4 contribution policy](https://github.com/Blockrazor/blockrazor/blob/master/CONTRIBUTING.MD) once more.

**Comment by gazhayes** [comment]
I merged this one, but yeah it does not follow the C4. This is well documented in the readme. Be sure to check the bad pull request roll of honour, read the contribution policy, and read the descriptive_c4.

**Pull request merged**
