### PR TITLE
Problem: Krazor Home link doesn't open in a new tab

### PR DESCRIPTION
**Pull request by staronline1985**
Solution: Open website in new tab

### CODE REVIEW

**Comment by staronline1985** [comment]
Problem: When click on krazor Home, It should not full redirect to website only open new tab

**Comment by MadanBhandari** [comment]
@staronline1985 this is not according to C4

**Comment by staronline1985** [comment]
> @staronline1985 this is not according to C4

@MadanBhandari , Can you please explain what the issue with same , I have followed each step according to documentation.

**Comment by MadanBhandari** [comment]
@staronline1985 : First line of commit msg should be short (less than 50 char)

For eg. in this case the Problem part, you need to sort to less than 50 char like use `Problem: Krazor link should open in new tab #2055` and explain ho you solve on new line with `Solution : ......`

PS : You don't need to copy exact same as issue title, you can short this under 50 char with `#issue number`

And you can edit this commit msg by `git commit --amend`

**Comment by samuelralak** [comment]
Hi @staronline1985 I have modified your PR and the issue #2055 you opened related to this just to give you an idea/example of what is expected of you by the C4 protocol. You almost had it mate ;). Please follow a similar format when opening future issues/PRs. Keep this [contribution guideline](https://github.com/Blockrazor/blockrazor/blob/master/CONTRIBUTING.MD) close to heart :). Looking forward to more contributions from you.

**Pull request merged**
