### PR TITLE
Problem : currency details ui-ux not good

### PR DESCRIPTION
**Pull request by MadanBhandari**
Solution : Update UI-UX as per bootswatch, Currency details - feature section collapsible UI added, MainLayout now follow bootswatch

Related to #440 , #577

### CODE REVIEW

**Comment by gazhayes** [comment]
> feature section collapsible

This is kind of annoying and forces uses to use extra clicks. Instead, we can display the top x number of items and use a "show more" button or whatever. I'll log an issue for the backend stuff and then you can style it.

**Comment by MadanBhandari** [comment]
There was show/hide separate button before

**Comment by AshHimself** [comment]
I agree 100%, there is a lot going on in this few and find it hard to navigate around a little. Even clicking through comments I found the UX a little tedious.. not sure what the best solution is though :/

**Comment by gazhayes** [comment]
I'm not sure if you've done any more work on this, but if not, don't worry about adding the show/hide flagged thing back in, I think there's a better way now that we are using the load more thing.

**Pull request merged**
