### PR TITLE
problem: no breadcrumbs

### PR DESCRIPTION
**Pull request by AshHimself**
solution: add breadcrumbs on each page and remove existing headers #1796

### CODE REVIEW

**Comment by AshHimself** [comment]
Checking into why it failed.

**Comment by AshHimself** [comment]
ohhh.. its merged and now I can't check :/

**Comment by gazhayes** [comment]
It's Jest. I don't think we are actually using Jest for any tests, if so the whole thing could be removed.

**Comment by anbud** [comment]
Yap, jest can be removed, there's only one jest test and it's not doing anything.

**Pull request merged**
