### PR TITLE
Problem: /addcoin unresponsive

### PR DESCRIPTION
**Pull request by janat08**
Solution: tooltips top. and something to do with the fields. #488

### CODE REVIEW

**Comment by gazhayes** [comment]
Conflicts again. Did you sync your master branch before making a branch?

**Comment by janat08** [comment]
the previous pull request wasn't merged, I don't know if I should create branch from master or pull request. My app always syncs master.

**Comment by gazhayes** [comment]
Seems to be ok now anyway. 

> My app always syncs master.

Which app are you using?

**Comment by janat08** [comment]
GitKraken

**Comment by janat08** [comment]
I think I just branched from master and redid previous pull/commit

**Comment by gazhayes** [comment]
Ok, these things are sometimes unavoidable anyway with many contributors and many pull requests coming in this fast.

**Pull request merged**
