### PR TITLE
Pull request from Swarandeep

### PR DESCRIPTION
**Pull request by Swarandeep1990**
Hi ,

I have successfully run project on my local machine .  You can check with below video link. 

http://recordit.co/IY0JSZrGiU.

I have read you job description and contribution policy and also applied for job. Below is my upwork profile link.

https://www.upwork.com/ab/proposals/966629849448165377

But can't understand for issue that you have mentioned. 

**There are issues in the issue tracker labeled "Bootstrap UX paid contributor assessment". These issues are used as an assessment for UX/UI applicants.**

Please explain me little bit more . I am open for more discussion with you . 

Email address :- swarandeep1logicerp@gmail.com

 I have willing to work on Meteor , Blaze , Mongodb and also bootstrap . I have more than 3 years experience with Meteor.js.

### CODE REVIEW

**Comment by sjmackenzie** [comment]
Sandeep, you mention you've read the contribution policy, but I highly doubt you have as the commit message is just "editfile".

**Comment by sjmackenzie** [comment]
Also you haven't actually solved anything. Closing this issue.

**Comment by Swarandeep1990** [comment]
Yes it was jut pull request , yes i did not do any changes .  Actually i can't understand the task that i have to solve. Can you please explain me little bit more or share the screen shot with me.

**Comment by Swarandeep1990** [comment]
I am available on skype also . pleas let me know if you want more discuss with me. I already have successfully setup project on my local machine.

**Comment by madguy02** [comment]
Please have a problem, solution based commit message, describe the problem and with two line skips, define the solution, refer other PRs as well. Thanks

**Comment by madguy02** [comment]
Can you please specify what are you trying to solve? PR from ``` name ``` is not proper

**Comment by Swarandeep1990** [comment]
@madguy02, @sjmackenzie   I did not understand the task  can you please explain So I can solve.

**Pull request closed without merging**
