### PR TITLE
[UI-UX] Currency container & card layout fix #1774 & #1776

### LINKED ISSUE #1774: Problem : [ / ] Currency container is too small
Problem : Currency container is too small, only one card on row.

screenshot from 2018-06-26 23-34-20

Solution : Fix layout, check responsive as well. Height should be auto, since this is an unlimited scroll page.

### PR DESCRIPTION
**Pull request by MadanBhandari**
Fix for #1774 & #1776

### CODE REVIEW

**Comment by samuelralak** [comment]
Hey there @MadanBhandari this PR was not C4 compliant.

**Comment by MadanBhandari** [comment]
Hey Sam, is this because of 2 commits or something else ?

**Comment by samuelralak** [comment]
Hey @MadanBhandari sorry, the PR title doesn't really the describe the problem - it doesn't identify the problem but rather only states a fix. There's also no description as to how you solved or applied your fix.

The commits are fine as long as they are solving two seperate problems.

**Comment by MadanBhandari** [comment]
@samuelralak Thanks for the clarification, I'll will keep this in mind for future PRs.

**Comment by samuelralak** [comment]
awesome stuff

**Pull request merged**
