### PR TITLE
Problem: lighthouse audit font size is too small 50% of time (#1398)

### PR DESCRIPTION
**Pull request by gdevdeiv**
Solution: Make base font-size larger

### CODE REVIEW

**Comment by gdevdeiv** [comment]
Seems that it broke some tests that require certain elements to be in a defined position to be tested.. looking into that next.

**Comment by anbud** [comment]
@gdevdeiv, don't worry about it, you didn't break anything, the test was broken in #1529, and has been fixed in #1532.

**Comment by gazhayes** [comment]
@gdevdeiv FYI we are using a new blockrazor stylesheet now instead of lux, it was implemented in #1468 
I'm not even sure why the lux sheet still exists, it should be gone.

**Comment by gdevdeiv** [comment]
Huh. I couldn't make CSS changes any other way, so I guess we are in fact STILL using the lux.min.css stylesheet. Should we review this?

**Comment by gazhayes** [comment]
Yes absolutely, we shouldn't be using lux, could you log an issue and maybe take it? There should be a blockrazor style sheet somewhere. Sorry, using phone so it's hard to check stuff properly.

**Pull request merged**
