### PR TITLE
Problem : Email password is in code #1921

### PR DESCRIPTION
**Pull request by MadanBhandari**
Solution : 

1. Email settings moved to `settings.json`
2. `Readme` updated for meteor settings
3. `settings.json` added to `.gitignore`

### CODE REVIEW

**Comment by MadanBhandari** [comment]
We need to pass `settings.json` by `meteor --settings settings.json` on production, I believe this the reason for failed build.

ping @gazhayes @anbud

**Comment by geekyd** [comment]
Lets move the config to `.env` instead of using a json for storing credentials. 
@gazhayes @MadanBhandari @anbud What do you think?

**Comment by gazhayes** [comment]
Yeah we're running node in production so better to use node env settings not meteor

**Comment by MadanBhandari** [comment]
Okay, I am looking into this.

**Comment by gazhayes** [comment]
Can you validate on production, let me know if you need server side logs.

**Pull request merged**
