### PR TITLE
problem:we are using two versions of bootstrap

### PR DESCRIPTION
**Pull request by AshHimself**
solution:Remove Bootstrap beta version and only use the Bootstrap JS file and not the CSS as we are using the Bootswatch custom CSS file. #1133.

### CODE REVIEW

**Comment by gazhayes** [comment]
npm WARN bootstrap@4.1.0 requires a peer of popper.js@^1.14.0 but none is installed. You must install peer dependencies yourself.

**Comment by gazhayes** [comment]
Manually installed on production to get it back up but it will uninstall on next merge.

**Comment by AshHimself** [comment]
Can we add npm install to the load script? or will that slow things down.

**Comment by gazhayes** [comment]
Yes this needs to happen (I'm working on it) but it won't resolve it in this case. You need to install locally and commit the change before meteor npm install will work on the server

**Pull request merged**
