### PR TITLE
Problem: users might add a currency that is already in the moderation queue #202

### PR DESCRIPTION
**Pull request by janat08**
Solution: call check in submit method, and used check in template state to prevent submit cutting off sanity checks within submit method. #202

### CODE REVIEW

**Comment by sjmackenzie** [comment]
Please read the contribution guide and correct your git commit message.

**Comment by sjmackenzie** [comment]
Nearly there, your "Solution: brief description of solution is weak", please try again.

**Comment by janat08** [comment]
Edited.

**Comment by sjmackenzie** [comment]
I take it you didn't read the contributing guideline. If you had you'd realize I'm referring to you `commit message`. Please become familiar with the contributing guidelines.

In other words, your commit message should be this:

```
Problem: users might add a currency that is already in the moderation queue #202

Solution: add check in submit method, and used check in template state to prevent submit cutting off sanity checks within submit method.
```

Please notice the empty line

**Comment by janat08** [comment]
I was told to adjust to other pull requests wherein you'll find that this format is hardly upheld. Anyway I'll read the explanation to try and commit it to memory.

**Comment by sjmackenzie** [comment]
Okay I'm going to give this one more try. 

Please *make* it fit and is nicely readable. Secondly you have *two* problem statements, which are *exactly the same*!?
Now *normally* if you have a complex problem *then* you use the first problem statement to *briefly* describe the problem and the second line to *further* elaborate on the problem, *if* *not* *then* you just have *one* problem statement.

If you could please read and understand the contribution guideline you'll make my life easier.

**Comment by janat08** [comment]
https://github.com/Blockrazor/blockrazor/blob/master/CONTRIBUTING.MD doesn't at all mention anything of the above, and as I said other pull requests don't comply with base requirements to begin with. The line by line rationale and history within the linked is broken.

**Comment by janat08** [comment]
I belief the commit title will fit in log.

**Comment by gazhayes** [comment]
@janat08  It looks like this is pretty much right, after the amendments, except for the 50 character limit for the first line.

You are completely right, there are past commits in the Blockrazor repo that do not comply with this (even some of my ones), but we are starting to be more brutal about enforcing it because it's causing problems when working offline or in a terminal without github open.

**Comment by janat08** [comment]
I mean a reference would be good, I didnt know if "message" encompasses
title and comment which then makes blank line excessive.

**Comment by gazhayes** [comment]
2.3(7): A patch commit message MUST consist of a single short (less than 50 characters) line stating the problem ("Problem: ...") being solved, followed by a blank line and then the proposed solution ("Solution: ...").

You can add more details after the blank line if there's not enough space in the 50 character 'heading'. The most important thing is that the first line does not exceed 50 characters and that it makes sense, so that someone who can't see the rest of the message still has a good idea about what you are doing.

**Comment by janat08** [comment]
I meant a reference pull request, I take it first line is to be the title
of commit, with rest going into commit comments?

I work with GUI app for github, so I suppose the CLI doesn't actually have
the separation of commit message into title and comments.

**Comment by janat08** [comment]
Do I go take another stab at it?

**Comment by gazhayes** [comment]
>Do I go take another stab at it?

Yes, please do :)

**Comment by gazhayes** [comment]
I'm not sure about the GUI, but to do this with the CLI I have written instructions in the Readme file.

**Comment by gazhayes** [comment]
> I take it first line is to be the title of commit, with rest going into commit comments?

The first 50 characters on the first line of the commit message ends up being the commit 'title', if you write anything longer than that it ends up in the commit 'message' (in the GUI). In the C4, the commit "message" is talking about the git commit message when using the CLI, I'm not sure what the github GUI app calls it.

**Pull request closed without merging**
