### PR TITLE
Problem: Can't create exchange at [/addcoin] (#1454)

### PR DESCRIPTION
**Pull request by anbud**
Solution: Fix the exchange creation logic so the exchange is added to the typeahead list. Add a callback function to `create` method that's called when data is created. Fix the `find` method in `LocalizableCollection`.

### CODE REVIEW

**Comment by janat08** [comment]
There's nothing inherently wrong with typeahead, it can be used in currency details (the create function).

**Comment by janat08** [comment]
Ill go continue writing webdriver tests.

**Comment by janat08** [comment]
Although there was another bad commit that removed create event autorun capability that was suppose to be revereted. Otherwise what happened was that the typeahead populated itself with transcient option (by method call), while results could be shown with no subscription.

**Comment by janat08** [comment]
Adding another param which none of other implementations use, that has supposedly required code wasn't great idea. Anyway that event is legacy, and if the nx.framework template for noneFound doesn't call that then it may as well be deleted.

**Comment by anbud** [comment]
@janat08, the callback is required. Try using it without it, the subscription alone won't fix it. There's a small lag when data is being created, so the `updateSource` method will be called too soon and it won't fetch new data. `beforeAdded` has to be used if you want to use limit or sort, but it doesn't default to it in other cases.

**Comment by janat08** [comment]
there's autorun that's suppose to react to changes, the call in event is to clear input. With the #1517 it might decide to go back to working as previously it would've only reset TT menu only if rererun was triggered by event.

**Comment by janat08** [comment]
BeforeAdded is supposed to be significantly more expensive then added.

**Pull request merged**
