### PR TITLE
Problem : Login, signup page doesn't look nice

### PR DESCRIPTION
**Pull request by MadanBhandari**
Solution : Update ui-ux of login, signup page

### CODE REVIEW

**Comment by gazhayes** [comment]
> Problem : Social media login in signup

Why is this a problem?

**Comment by MadanBhandari** [comment]
There was no functionality to signup with facebook and github, only UI was mistakenly copied from login page.

We can add there too, if needed. Login/Signup using facebook and github is same logic right ? I will try and will update in next PR.

**Comment by gazhayes** [comment]
The new signup/login page looks awesome!

One problem though, the email login/signup is only temporary while we are developing, it won't be used when we go public due to issue #39

**Comment by gazhayes** [comment]
Facebook/github signup is working (or, was working).

Did you test it on blockrazor.org, or locally?

**Comment by MadanBhandari** [comment]
Same Error : Email is already in use.

I have only updated UI (HTML, CSS), I didn't change any logic.

**Comment by gazhayes** [comment]
You get that error when you try to sign up with facebook?

**Comment by MadanBhandari** [comment]
I tried on my local master, before megring this PR

**Comment by gazhayes** [comment]
How about on the production server?

I'm trying to replicate the error

**Comment by MadanBhandari** [comment]
I am not sure about production server. I just run `meteor` without any settings attached and export `ROOT_URL=https://blockrazor.org`

**Comment by gazhayes** [comment]
For local server it's different. Check the readme.

**Pull request merged**
