### PR TITLE
Problem: Cannot use inverse ELO rating for comparison questions (#29)

### PR DESCRIPTION
**Pull request by anbud**
Solution: Add a way to mark questions as negative and inverse ELO accordingly

### CODE REVIEW

**Comment by gazhayes** [comment]
@anbud can you implement this for the question "which has the most annoying questions" (it's one of the wallet questions). Please fully document so that other people can easily apply it to new questions.

**Comment by anbud** [comment]
@gazhayes, I'll send another PR soon, with a way to add the negative flag from the moderator panel (questions page), I believe that would be the easiest way to use it.

**Comment by anbud** [comment]
Done in #142, you can use /questions for everything.

**Comment by gazhayes** [comment]
Thanks, that is absolutely perfect.

**Pull request merged**
