### PR TITLE
Problem: wrong format for topNav kzr balance #1671

### PR DESCRIPTION
**Pull request by samuelralak**
Solution: properly formatting balance amount before upsert. introduced global helper to format balance amount for both topNav and sideNav

### CODE REVIEW

**Comment by anbud** [comment]
Hey, 

The test is failing as it expects a numerical value for the balance field and you've changed it to a string. 

Do you want to fix the test or should I? :) Fixing it just requires changing $inc to $set in hashpower.test.js (or something similar), as you did in the `creditUserWith` method.

**Comment by samuelralak** [comment]
@anbud let me give it a try

**Comment by anbud** [comment]
Sorry about that, I was wrong, the error is not in the test, it's caused by `removeUserCredit` method, as it's still expecting a numerical value for `balance`.

**Comment by samuelralak** [comment]
@anbud the tests are passing now

**Pull request merged**
