### PR TITLE
Problem: no typeahead template reuse, no encapsulated local collection

### PR DESCRIPTION
**Pull request by janat08**
Solution: made typeahead template, but didn't switch /auctions to it. #863 Made typeahead react to prop for db query so that reactive changes to query can happen outside the template. #872 Made collection methods that encapsulate logic for using fast-render but switching to method results in local collection. #873

### CODE REVIEW

**Comment by janat08** [comment]
I believe I should've tried to at least split this between commits. the code for encapsulating local collection logic is in utilities.

**Comment by gazhayes** [comment]
Its no big deal since its already done, you can keep it in mind next time though.

**Comment by gazhayes** [comment]
Looks like this will break master (based on the test)

**Comment by janat08** [comment]
i'll update the test.

**Comment by janat08** [comment]
although I have no clue where it is, as it is not in proper location.

**Comment by janat08** [comment]
not updating.

**Comment by gazhayes** [comment]
The tests themselves aren't breaking. There's errors in your code that break master so tests never run.

**Comment by gazhayes** [comment]
Does it build locally for you?

**Comment by gazhayes** [comment]
TypeError: LocalizableCollection is not a constructor
W20180401-23:53:11.198(0)? (STDERR)     at currencies.js (imports/api/coins/currencies.js:4:27)

**Comment by janat08** [comment]
yes it didn't, but I pushed changes and realized there're still errors.

**Comment by gazhayes** [comment]
Just close this one, then you can send a new one without the rebase commit and without breaking master ;)

**Comment by janat08** [comment]
it keeps finding freaking conflicts to resolve even if it's essentially same code I'm pushing.

**Comment by gazhayes** [comment]
Oh you sent one just as I closed it

**Comment by gazhayes** [comment]
Yep, its because you have the first one already. This is why its important to rebase just before you send a pull request, otherwise you will have multiple conflicts. I suggest closing this pull request and sending a new one that is based on current master.

**Comment by janat08** [comment]
I just tried merging master before force pushing.

**Comment by gazhayes** [comment]
If you have "resolved" conflicts you cant edit or send more commits without creating new conflicts. Your local branch is out of date. Make a new branch off current master and rebase all your changes on that. Then there will be no conflicts.

**Comment by gazhayes** [comment]
And always verify that Meteor actually runs before committing anything, we do **not** break master.

**Pull request closed without merging**
