### PR TITLE
Problem: mongo subscriptions don't start and end correctly

### PR DESCRIPTION
**Pull request by janat08**
https://github.com/Blockrazor/blockrazor/issues/34
Solution: Bind autorun to template instances and declare subscription.

FlowRouter route to addcoin involves subscription that I'm unsure that it requires change.
Changed ratings.js readiness callback.

### CODE REVIEW

**Comment by sjmackenzie** [comment]
No worries, pls keep the problem/solutions in git messages, allowing non-github users to easily see *why* changes were made. Reading the code tells *what* the changes were. If you wish you can just duplicate the git problem/solution messages into the PR title or create an over arching problem/solution at PR level if there are multiple commits under one PR which solve that over arching problem.

**Comment by sjmackenzie** [comment]
You can amend a git commit message then force push to the same branch. This will correct the git message.

**Comment by sjmackenzie** [comment]
Okay I see the "solution" section of the git message is missing. Please read the readme on how to correctly format the git message and try again.

**Comment by janat08** [comment]
*Read it carefully.

**Comment by sjmackenzie** [comment]
The commit message should be this:

```
problem: mongo subscriptions don't start and end correctly

solution: bind autorun to template instances and declare subscription.
```

**Pull request merged**
