### PR TITLE
problem: cannot bid low amount on auction

### PR DESCRIPTION
**Pull request by AshHimself**
solution: modify stepper on number element to include ANY decimal value #1489'

### CODE REVIEW

**Comment by samuelralak** [comment]
@AshHimself can you do it locally?

**Comment by samuelralak** [comment]
@AshHimself a little curious, how did you end up with two similar commits?

**Comment by AshHimself** [comment]
Honestly not sure.. guessing I committed twice. Close the PR if needed and
can send again.

**Comment by gazhayes** [comment]
@AshHimself yeah just send again.

**Pull request closed without merging**
