### PR TITLE
Problem : Filter in wallet is not clear #929

### PR DESCRIPTION
**Pull request by MadanBhandari**
Solution : Content updated for filter options, No of Rows per page and pagination moved to top for better User Experience

Fix for #929

### CODE REVIEW

**Comment by MadanBhandari** [comment]
`wallet-item.scss` file renamed to` wallet.scss`, just because this will be common css for whole wallet page.

**Comment by chamidu-supeshala** [comment]
@gazhayes I cannot create a PR for #924 until this is merged, otherwise conflicts may definitely occur.

**Comment by sjmackenzie** [comment]
@MadanBhandari do be careful editing code by adding whitespace cause it looks good. @gazhayes there should be a styleguide for folks to work to. This helps prevent conflicts and your editor can do the heavy lifting.

**Comment by MadanBhandari** [comment]
>  do be careful editing code by adding/removing whitespace cause it looks good. 

I only do alignment changes in my work space, otherwise I don't only edit whatspace.

> there should be a styleguide for folks to work to. This helps prevent conflicts and your editor can do the heavy lifting.

Yes, there should be. Issue is already created for this #934.

**Pull request merged**
