### PR TITLE
Problem: compare currencies doesn't link to currencies

### PR DESCRIPTION
**Pull request by janat08**
Solution: icon to the left for generic link icon, rather than external link since fortawesome site breaks on trying to look up fontawesome set: https://fortawesome.com/sets/font-awesome

### CODE REVIEW

**Comment by gazhayes** [comment]
font awesome isn't working for you?

**Comment by janat08** [comment]
I can't find class name for icon since the website that should do it is broke, so used generic one that mapped over from font awesome literally.

**Comment by AshHimself** [comment]
There are two version of fontawesome, ensure you are using 4.7 font class
naming convention.

**Comment by janat08** [comment]
fixed icon.

**Pull request merged**
