### PR TITLE
Problem: home route UX does not show enough scope

### PR DESCRIPTION
**Pull request by MadanBhandari**
- Collapsible side navigation
- Find/Filter form updated
- Currency card - minimal info on homepage

### CODE REVIEW

**Comment by sjmackenzie** [comment]
Please correct your commit messages. Please first understand the contribution guideline.

**Comment by MadanBhandari** [comment]
@sjmackenzie you mean, I should add problem (Problem : home route UX does not show enough scope)  in every msg or should I committ all files at once ? 

This is my first PR, contribution guide says, add all files one by one with commit message.

**Comment by gazhayes** [comment]
@sjmackenzie: @MadanBhandari is completely new to git and github.

@MadanBhandari: I see where you went wrong:
`git add changed_file.js //repeat for each file you changed`

This doesn't mean `commit` for each file changed, just `add` each changed file before committing. We say it this way in the guide so that people new to Git don't add everything at once. You can do `git add -A` to add *all* changes at once but that is dangerous and can have unintended consequences if you don't know what you're doing.

Your commit messages are definitely no good, they need to comply with the C4 contribution protocol. You could split this into maybe two commits:

Problem: no sidebar navigation
Problem: home route does not show enough scope

In addition to this, you need to rebase these changes on the current master branch because there are conflicts (someone else edited the same code you did). It looks like you did this just before sending the pull request, which is the correct thing to do, but there have been two commits since you did this (probably happened after you sent the pull request). Since you have to rework it anyway you may as well rebase it again.

**Comment by MadanBhandari** [comment]
@gazhayes : Thanks for the explanation. I will send PR with updated commit messages :)

**Comment by MadanBhandari** [comment]
Quick question : Do I need to close this PR and send new one ?

**Comment by gazhayes** [comment]
> Quick question : Do I need to close this PR and send new one ?

Yeah just send a new pull request.

**Pull request closed without merging**
