### PR TITLE
problem: moderator page is ugly

### PR DESCRIPTION
**Pull request by AshHimself**
solution: bootwatchified moderator page #908

### CODE REVIEW

**Comment by gazhayes** [comment]
@AshHimself looks like you broke something here ;)

**Comment by AshHimself** [comment]
oh dear... let me look at it now.

**Comment by AshHimself** [comment]
What did you think was broken? I got an empty screen but I think that's just because there was no UX to say there was no data.. I added a community image for approval and now see data

**Comment by gazhayes** [comment]
Oops. You're right. Sorry.

**Pull request merged**
