### PR TITLE
problem: menu does not allow sub menus

### PR DESCRIPTION
**Pull request by AshHimself**
solution: complete refactor of the menu #946

### CODE REVIEW

**Comment by AshHimself** [comment]
If not, leme delete and resend and somehow delete my tard two commeits.

**Comment by AshHimself** [comment]
@gazhayes oh shit.. I merged it when I tried to squash it.. should I step back now being I broke C4.

**Comment by gazhayes** [comment]
You merged it! Ok, bit of a mistake, just write this off as a screw up and try not to do that again.

**Comment by AshHimself** [comment]
Yeh sorry mate.. I think what I did was that I made a commit, then I did a git pull upstream master and then had conflicts, I fixed the conflicts then committed again which is why I got two.

Should of removed first commit before fixing the merge issues?

**Comment by gazhayes** [comment]
What I usually do in these situations is make all my changes, don't commit anything, use git stash, then I pull from upstream to my local master, make a new branch, git stash pop, then commit and push then pull request.

**Comment by AshHimself** [comment]
Got it! clear as mud.

**Pull request merged**
