### PR TITLE
Problem: It's not clear to casual viewers how active the site is.

### PR DESCRIPTION
**Pull request by janat08**
Solution: Near "found x results" in [/] shows "; Users online: 1/46" #882. Isn't as efficient as I had hoped.

### CODE REVIEW

**Comment by gazhayes** [comment]
@anbud can you look at this test?

**Comment by anbud** [comment]
@gazhayes, cache issue again, they're working properly again now.

**Comment by gazhayes** [comment]
Does that mean it resolved itself? Or did you do something? Sorry if you've mentioned this before I can't remember.

**Comment by anbud** [comment]
@gazhayes, I believe I did, but don't worry, I can repeat it once more. :)

Basically, Travis CI caches Meteor builds in order to run tests faster. Now, when we add a new package to Meteor, Travis' cache is not updated, so tests begin to fail.
It would resolve itself after a few days when the cache gets too old, but, for an immediate fix, we just need to go [here](https://travis-ci.org/Blockrazor/blockrazor/caches) and click on `Delete all repository caches` to fix it.

**Pull request merged**
