### PR TITLE
Problem: deffer save prefferences

### PR DESCRIPTION
**Pull request by janat08**
Solution: is broken at trying to overwrite Meteor.logout(), @anbud asked for PR, #565.

### CODE REVIEW

**Comment by janat08** [comment]
the overwriting code is in startup folder.

**Comment by gazhayes** [comment]
The test is failing. Is it working locally for you?

test error: "imports/ui/layouts/mainLayout/mainLayout.js:114: Unexpected token (114:0)"

**Comment by gazhayes** [comment]
the commit message could be better too ;)

**Comment by janat08** [comment]
this pull isn't actually meant to work, although from what I remember an error message would show up somewhere about it it not working.

**Pull request merged**
